front/mysite/urls.py
#;mysite

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

front/polls/urls.py
from django.urls import path

from django.conf.urls import include, url
from django.contrib import admin

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('add_file_acc/', views.add_file_acc, name='add_file_acc'),
    path('add_directory_acc/', views.add_directory_acc, name='add_directory_acc'),
    path('delete_directory/<int:directory_id>/', views.delete_directory_number, name='delete_directory_number'),
    path('delete_file/<int:file_id>/', views.delete_file_number, name='delete_file_number'),
    path('login/', views.login, name='login'),
    path('login/terminate/', views.login_terminate, name='login_terminate'),
    path('register/', views.register, name='register'),
    path('register/terminate/', views.register_terminate, name='register_terminate'),
    path('logout/', views.logout, name='logout'), 
    path('get_json_data/', views.get_json_data, name='get_json_data'),
    path('get_json_data/files/', views.get_json_data_files, name='get_json_data_files'),
    path('get_json_data/<int:dir_id>/', views.get_json_data_directory, name='get_json_data_directory'),
    path('get_json_data/<int:dir_id>/<int:file_id>/', views.get_json_data_file, name='get_json_data_file'),
    path('make_group_project/', views.make_group_project, name='make_group_project'),
    path('get_group_projects/', views.get_group_projects, name='get_group_projects'),
    path('get_project/<int:id>/', views.get_project, name='get_project'),
    path('get_task/<int:id>/<int:task_id>/', views.get_task, name='get_task'),
    path('delete_group_project/<int:id>/', views.delete_group_project, name='delete_group_project'),
    path('get_group_tasks/', views.get_group_tasks, name='get_group_tasks'),
    path('delete_task/<int:id>/', views.delete_task, name='delete_task'),
    path('add_group_task/', views.add_group_task, name='add_group_task'),
    path('notification/', views.notification, name='notification'),
]

front/polls/models.py
import datetime

from django.db import models
from django.utils import timezone
import os

class Group_project(models.Model):
    owner = models.CharField(max_length=100)
    coowner = models.CharField(max_length=100)
    optional_description = models.CharField(max_length=500)
    name = models.CharField(max_length=100)
    pub_date = models.DateTimeField('date published')
    validity_flag = models.BooleanField()
    
class Group_task(models.Model):
    project_name = models.CharField(max_length=100)
    optional_description = models.CharField(max_length=500)
    name = models.CharField(max_length=100)
    pub_date = models.DateTimeField('date published')
    validity_flag = models.BooleanField()

class FramaOutput(models.Model):
    phrase = models.CharField(max_length=200)
    output = models.CharField(max_length=30000)
    
    def __str__(self):
        return self.phrase
        
    def outputt(self):
        return self.output


class User(models.Model):
    name = models.CharField(max_length=30)
    login = models.CharField(max_length=30)
    password = models.CharField(max_length=50)
    pub_date = models.DateTimeField('date published')
    validity_flag = models.BooleanField()
    
    def __str__(self):
        return self.login
        
    def passw(self):
        return self.password
    


class Status_data(models.Model):
    status_data_field = models.CharField(max_length=1000)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.status_data_field
        
class Directory(models.Model):
    name = models.CharField(max_length=50)
    optional_description = models.CharField(max_length=500, blank=True)
    creation_date = models.DateTimeField('creation_date')
    owner = models.CharField(max_length=30)
    validity_flag = models.BooleanField()
    
    def __str__(self):
        return self.name
    def ret_name(self):
        return self.name
    def is_active(self):
        return self.validity_flag
            
class Section_status(models.Model):
    status_data_field = models.CharField(max_length=1000)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField('date_published')
    validity_flag = models.BooleanField()
    
    def __str__(self):
        return self.status_data_field
    
class Section_category(models.Model):
    category = models.CharField(max_length=50)
    pub_date = models.DateTimeField('date_published')
    validity_flag = models.BooleanField()
    
    def __str__(self):
        return self.category
        
class File(models.Model):
    name = models.CharField(max_length=50)
    optional_description = models.CharField(max_length=500, blank=True)
    creation_date = models.DateTimeField('creation_date')
    owner = models.CharField(max_length = 30)
    validity_flag = models.BooleanField()
    directory_name = models.CharField(max_length=50)
    filepath= models.FileField(upload_to='files', verbose_name="")
    def __str__(self):
        return self.name
    def ret_name(self):
        return self.name
    def ret_owner(self):
        return self.owner
    def is_active(self):
        return self.validity_flag
    def ret_content(self):
        return self.filepath
        
class File_section(models.Model):
    name = models.CharField(max_length=50, blank=True)
    optional_description = models.CharField(max_length=500, blank=True)
    creation_date = models.DateTimeField('date_published')
    owner = models.CharField(max_length=30)
    validity_flag = models.BooleanField()
    file = models.CharField(max_length=30)
    def __str__(self):
        return self.name
    def ret_name(self):
        return self.name
    def ret_owner(self):
        return self.owner
        
        
class Group(models.Model):
    name = models.CharField(max_length=50, blank=True)
    login_1 = models.CharField(max_length=50, blank=True)
    login_2 = models.CharField(max_length=50, blank=True)
    creation_date = models.DateTimeField('date_published')


            

front/polls/views.py
from django.shortcuts import get_object_or_404, render, redirect


from django.http import JsonResponse

import json


import requests

notif = False

coowner_project = False

def notification(request):
    if request.method == 'POST':
        print(request.POST)
        coowner = request.POST['coowner']
        project_name = request.POST['project_name']
        date = request.POST['date']
        print(coowner)
        global coowner_project
        coowner_project = coowner
        global notif
        notif = 'new project:' + str(project_name) + ' made in ' + str(date)
        print('bleee' + str(notif))
        
        return JsonResponse({}, status=200);
    else:
        return JsonResponse({}, status=400);

def add_group_task(request):
    if request.method == 'POST':
        print(request.POST)
        json_data = {
            'optional_description': request.POST.get('optional_description'),
            'directory_name': request.POST.get('directory_name'),
            'filename': request.POST.get('filename')
        }
        response = requests.post('http://groups-docker.herokuapp.com/groups/add_group_task/',data=json_data)
        return redirect('/polls/')
    else:
        return JsonResponse({}, status=400);

def delete_task(request, id):
    response = requests.get('http://groups-docker.herokuapp.com/groups/delete_task/' + str(id) + '/')
    print(response.content)
    return redirect('/polls/')
    

def get_group_tasks(request):
    if request.method == 'GET':
        response = requests.get('http://groups-docker.herokuapp.com/groups/get_group_tasks')
        print(json.loads(response.content))
        return JsonResponse(json.loads(response.content), status=200, safe=False)
    else:
        return JsonResponse({}, status=400)  

def delete_group_project(request, id):
    response = requests.get('http://groups-docker.herokuapp.com/groups/delete_group_project/' + str(id) + '/')
    return redirect('/polls/')

def get_task(request, id, task_id):
    if request.method == 'GET':
        response = requests.get('http://groups-docker.herokuapp.com/groups/get_task/' + str(id) + '/' + str(task_id) + '/')
        print(json.loads(response.content))
        return JsonResponse(json.loads(response.content), status=200, safe=False)

    else:
        return JsonResponse({}, status=400)

def get_project(request, id):
    if request.method == 'GET':
        response = requests.get('http://groups-docker.herokuapp.com/groups/get_project/' + str(id) + '/')
        print(json.loads(response.content))
        return JsonResponse(json.loads(response.content), status=200, safe=False)
    else:
        return JsonResponse({}, status=400) 

def get_group_projects(request):
    if request.method == 'GET':
        response = requests.get('http://groups-docker.herokuapp.com/groups/get_group_projects/' + str(request.session['login']) + '/')
        print(json.loads(response.content))
        return JsonResponse(json.loads(response.content), status=200, safe=False)
    else:
        return JsonResponse({}, status=400)  
        

def make_group_project(request):
    if request.method == 'POST':
        print(request.POST)
        json_data = {
            'cooperator': request.POST.get('cooperator'),
            'optional_description': request.POST.get('optional_description'),
            'owner': request.session.get('login'),
            'filename': request.POST.get('filename')
        }
        response = requests.post('http://groups-docker.herokuapp.com/groups/make_group_project/',data=json_data)
        return redirect('/polls/')
    else:
        return JsonResponse({}, status=400);

def get_json_data(request):
    if request.method == 'GET':
        response = requests.get('http://users-docker.herokuapp.com/users/get_json_data/' + request.session['login'] + '/')
        print(json.loads(response.content))
        return JsonResponse(json.loads(response.content), status=200, safe=False)
    else:
        return JsonResponse({}, status=400) 
        
def get_json_data_files(request):
    if request.method == 'GET':
        response = requests.get('http://users-docker.herokuapp.com/users/get_json_data_files/' + request.session['login'] + '/')
        print(json.loads(response.content))
        return JsonResponse(json.loads(response.content), status=200, safe=False)
    else:
        return JsonResponse({}, status=400) 
        
def get_json_data_directory(request, dir_id):
    if request.method == 'GET':
        response = requests.get('http://users-docker.herokuapp.com/users/get_json_data_directory/' + str(dir_id) + '/')
        print(json.loads(response.content))
        return JsonResponse(json.loads(response.content), status=200, safe=False)
    else:
        return JsonResponse({}, status=400) 
        
        
def get_json_data_file(request, dir_id, file_id):
    if request.method == 'GET':
        response = requests.get('http://users-docker.herokuapp.com/users/get_json_data_file/' + str(dir_id) + '/' + str(file_id) + '/')
        print(json.loads(response.content))
        return JsonResponse(json.loads(response.content), status=200, safe=False)
    else:
        return JsonResponse({}, status=400)    

def add_file_acc(request):
    if  not 'login' in request.session:
        request.session['login'] = False
    if  not 'Unhide' in request.session:
        request.session['Unhide'] = True
    if request.method == 'POST':
        if request.POST.get('directory_name') and request.POST.get('optional_description') and request.POST.get('filename'):
            json_data = {
                'directory_name': request.POST.get('directory_name'),
                'optional_description': request.POST.get('optional_description'),
                'owner': request.session['login'],
                'filename': request.POST.get('filename')
            }
            response = requests.post('http://users-docker.herokuapp.com/users/add_file_acc/',data=json_data)
    
    return redirect('/polls/')
    
    
def delete_file_number(request, file_id):
    if request.method == 'GET':
        response = requests.get('http://users-docker.herokuapp.com/users/delete_file/' + str(file_id) + '/')
        return redirect('/polls/')
    else:
        return JsonResponse({}, status=400)    

    
    
def delete_directory_number(request, directory_id):
    if request.method == 'GET':
        response = requests.get('http://users-docker.herokuapp.com/users/delete_directory/' + str(directory_id) + '/')
        return redirect('/polls/')
    else:
        return JsonResponse({}, status=400)    
    
    
def add_directory_acc(request):
    if  not 'login' in request.session:
        request.session['login'] = False
    if  not 'Unhide' in request.session:
        request.session['Unhide'] = True
    if request.method == 'POST':
        if request.POST.get('directory_name'):
            json_data = {
                'directory_name': request.POST.get('directory_name'),
                'owner': request.session['login']
            }
            response = requests.post('http://users-docker.herokuapp.com/users/add_directory_acc/',data=json_data)
    
    return redirect('/polls/')
    
def login(request):
    context = {}
    return render(request, 'polls/login.html', context)
    
def login_terminate(request):
    if request.method == 'POST':
        print(request.POST)
        json_data = {
            'login': request.POST.get('login'),
            'password': request.POST.get('password')
        }
        response = requests.post('http://users-docker.herokuapp.com/users/login_terminate/',data=json_data)
        print(response)
        if response.status_code == 200:
            request.session['login'] = request.POST.get('login')
            return redirect('/polls/')
    
    context = {'login_error': 'Incorrect login or password'}
    return render(request, 'polls/login.html', context)
    
    
def register(request):
    context = {}
    return render(request, 'polls/register.html', context)
    
def register_terminate(request):
    if request.method == 'POST':
        print(request.POST)
        json_data = {
            'login': request.POST.get('login'),
            'password': request.POST.get('password'),
            'password_again': request.POST.get('password_again')
            }
        response = requests.post('http://users-docker.herokuapp.com/users/register_terminate/',data=json_data)
        print(response)
        if response.status_code == 200:
            request.session['login'] = request.POST.get('login')
            return redirect('/polls/')
    
    context = {'login_error': 'Incorrect login or password or password_again'}
    return render(request, 'polls/register.html', context)
    
def logout(request):
    request.session['login'] = False
    return redirect('/polls/')

def index(request):
    if not 'login' in request.session:
        request.session['login'] = False
    
    if request.session['login'] == False:
        return render(request, 'polls/index.html', {})
    
    response = requests.get('http://users-docker.herokuapp.com/users/get_json_data/' + request.session['login'] + '/')
    list = json.loads(response.content)
    print(list)
    print(notif)
    notify = False
    if request.session['login'] == coowner_project and coowner_project != False:
        notify = notif
        
    context = {
    'latest_directories_list': list,
    'login': request.session['login'],
    'notification': notify
    }
    return render(request, 'polls/index.html', context)

front/polls/templates/polls/add_directory.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>app interface</title>
<style>
</style>
</head>
<body>
	<link rel="stylesheet"  href="{% static 'css/view.css'  %}">

	<div class="menu_bar">
		<div class="dropdown">
		  <button class="dropbtn">Menu</button>
		  <div class="dropdown-content">
			<a href="/polls/add_file">Add file</a>
			<a href="/polls/add_directory">Add directory</a>
			<a href="/polls/delete_file">Delete file</a>
			<a href="/polls/delete_directory">Delete directory</a>
			<a href="/polls/">Main page</a>
		  </div>
		</div>
	</div>

	<div class="files_selecting_dialog_added">
	
	</div>

	<div class="files_selecting_dialog">
		<h4>Add file:</h4>
		<div class="btn-group">
			<form action="{% url 'polls:add_directory_acc' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
			Directory name:
			<input type="text" name="directory_name" required id="directory_id"/>
			Optional description:
			<input type="text" name="optional_description" required id="optional_id" size="30" style="height: 100px;"/>
			<br/>
			<input type="submit" value="Add"/>
			</form>
		</div>
	</div>

	<div class="text_field_for_program_code">
		<form action="www.html" method="get">
			<textarea  class="text_area" name="description">
			
			</textarea>
		</form>
	</div>

	<div class="focus_on_program_elements">
		<p>focus on program elements</p>
	</div>

	<div class="container_for_tab_data">
		<p>container for tab data</p>
	</div>

	<div class="tab_line">
		<div class="btn-line-group">
			<button>Provers</button>
			<button>VCs</button>
			<button>Result</button>
		</div>
	</div>

	</body>
</html>

front/polls/templates/polls/add_file.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>app interface</title>
<style>
</style>
</head>
<body>
	<link rel="stylesheet"  href="{% static 'css/view.css'  %}">

	<div class="menu_bar">
		<div class="dropdown">
		  <button class="dropbtn">Menu</button>
		  <div class="dropdown-content">
			<a href="/polls/add_file">Add file</a>
			<a href="/polls/add_directory">Add directory</a>
			<a href="/polls/delete_file">Delete file</a>
			<a href="/polls/delete_directory">Delete directory</a>
			<a href="/polls/">Main page</a>
		  </div>
		</div>
	</div>

	<div class="files_selecting_dialog_added">
	
	</div>

	<div class="files_selecting_dialog">
		<h4>Add file:</h4>
		<div class="btn-group">
			<form action="{% url 'polls:add_file_acc' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
			Directory:
			<input type="text" name="directory_name" required id="directory_id"/>
			Optional description:
			<input type="text" name="optional_description" required id="optional_id"/>
			Owner:
			<input type="text" name="owner" required id="owner_id"/>
			<input type="file" name="full_file" required id="full_file_id"/>
			<br/>
			<input type="submit" value="Add"/>
			</form>
		</div>
	</div>

	<div class="text_field_for_program_code">
		<form action="www.html" method="get">
			<textarea  class="text_area" name="description">
			
			</textarea>
		</form>
	</div>

	<div class="focus_on_program_elements">
		<p>focus on program elements</p>
	</div>

	<div class="container_for_tab_data">
		<p>container for tab data</p>
	</div>

	<div class="tab_line">
		<div class="btn-line-group">
			<button>Provers</button>
			<button>VCs</button>
			<button>Result</button>
		</div>
	</div>

	</body>
</html>

front/polls/templates/polls/add_file_acc.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>app interface</title>
<style>
</style>
</head>
<body>

	</body>
</html>

front/polls/templates/polls/delete_directory.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>app interface</title>
<style>
</style>
</head>
<body>
	<link rel="stylesheet"  href="{% static 'css/view.css'  %}">

	<div class="menu_bar">
		<div class="dropdown">
		  <button class="dropbtn">Menu</button>
		  <div class="dropdown-content">
			<a href="/polls/add_file">Add file</a>
			<a href="/polls/add_directory">Add directory</a>
			<a href="/polls/delete_file">Delete file</a>
			<a href="/polls/delete_directory">Delete directory</a>
			<a href="/polls/">Main page</a>
		  </div>
		</div>
	</div>

	<div class="files_selecting_dialog_added">
	
	</div>

	<div class="files_selecting_dialog">
		<div class="btn-group">
			{% if latest_directories_list %}
			<ul>
			{% for dir in latest_directories_list %}
			{% if dir.is_active %}
			<a href="/polls/delete_directory/{{ dir.id }}/"><button>{{ dir.ret_name }}</button></a>
			{% endif %}
			{% endfor %}
			</ul>
			{% endif %}
		</div>
	</div>

	<div class="text_field_for_program_code">
		<form action="www.html" method="get">
			<textarea  class="text_area" name="description">
			
			</textarea>
		</form>
	</div>

	<div class="focus_on_program_elements">
		<p>focus on program elements</p>
	</div>

	<div class="container_for_tab_data">
		<p>container for tab data</p>
	</div>

	<div class="tab_line">
		<div class="btn-line-group">
			<button>Provers</button>
			<button>VCs</button>
			<button>Result</button>
		</div>
	</div>

	</body>
</html>

front/polls/templates/polls/delete_file.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>app interface</title>
<style>
</style>
</head>
<body>
	<link rel="stylesheet"  href="{% static 'css/view.css'  %}">

	<div class="menu_bar">
		<div class="dropdown">
		  <button class="dropbtn">Menu</button>
		  <div class="dropdown-content">
			<a href="/polls/add_file">Add file</a>
			<a href="/polls/add_directory">Add directory</a>
			<a href="/polls/delete_file">Delete file</a>
			<a href="/polls/delete_directory">Delete directory</a>
			<a href="/polls/">Main page</a>
		  </div>
		</div>
	</div>

	<div class="files_selecting_dialog_added">
	
	</div>

	<div class="files_selecting_dialog">
		<div class="btn-group">
			{% if latest_files_list %}
			<ul>
			{% for file in latest_files_list %}
			{% if file.is_active %}
			<a href="/polls/delete_file/{{ file.id }}/"><button>{{ file.ret_name }}</button></a>
			{% endif %}
			{% endfor %}
			</ul>
			{% else %}
			<p>No files are available.</p>
			{% endif %}
		</div>
	</div>

	<div class="text_field_for_program_code">
		<form action="www.html" method="get">
			<textarea  class="text_area" name="description">
			
			</textarea>
		</form>
	</div>

	<div class="focus_on_program_elements">
		<p>focus on program elements</p>
	</div>

	<div class="container_for_tab_data">
		<p>container for tab data</p>
	</div>

	<div class="tab_line">
		<div class="btn-line-group">
			<button>Provers</button>
			<button>VCs</button>
			<button>Result</button>
		</div>
	</div>

	</body>
</html>

front/polls/templates/polls/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>app interface</title>
<style>
</style>
</head>
<body>
	<link rel="stylesheet"  href="{% static 'css/view.css'  %}">

	<div class="menu_bar">
		<div class="dropdown">
		  <button class="dropbtn">Menu</button>
		  <div class="dropdown-content">
			<a href="#">Link 1</a>
			<a href="#">Link 2</a>
			<a href="#">Link 3</a>
			<a href="#">Link 4</a>
			<a href="#">Link 5</a>
		  </div>
		</div>
	</div>

	<div class="files_selecting_dialog_added">
	
	</div>

	<div class="files_selecting_dialog">

	
		<div class="btn-group">
			<button>b1</button>
			<button>b2</button>
			<button>b3</button>
			<button>b4</button>
			<button>b5</button>
		</div>
	</div>

	<div class="text_field_for_program_code">
		<form action="www.html" method="get">
			<textarea  class="text_area" name="description">
			
			</textarea>
		</form>
	</div>

	<div class="focus_on_program_elements">
		<p>focus on program elements</p>
	</div>

	<div class="container_for_tab_data">
		<p>container for tab data</p>
	</div>

	<div class="tab_line">
		<div class="btn-line-group">
			<button>Provers</button>
			<button>VCs</button>
			<button>Result</button>
		</div>
	</div>

	</body>
</html>

front/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>